// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1g48_rOF9yZBhpPEJ74Srhv31aLh5XAY',
    appId: '1:705658275156:web:26b1bb1c6b8a77fdd7f4c1',
    messagingSenderId: '705658275156',
    projectId: 'comhub1-ee55e',
    authDomain: 'comhub1-ee55e.firebaseapp.com',
    storageBucket: 'comhub1-ee55e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVP0NaUe9LSzOOs5XacQLIirslgZHyb1E',
    appId: '1:705658275156:android:b3ab31dbdfcb65bad7f4c1',
    messagingSenderId: '705658275156',
    projectId: 'comhub1-ee55e',
    storageBucket: 'comhub1-ee55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHOUeC12xdtiFJjqrDn22iC0XCjSkWi7Y',
    appId: '1:705658275156:ios:3a3bd76663188d47d7f4c1',
    messagingSenderId: '705658275156',
    projectId: 'comhub1-ee55e',
    storageBucket: 'comhub1-ee55e.appspot.com',
    iosClientId: '705658275156-nr6pdgjfhvchren1ql6jpvhs00gunusf.apps.googleusercontent.com',
    iosBundleId: 'com.example.comhub1',
  );
}
